import { Model, DataTypes } from 'sequelize';

import { sequelize } from '@/db';
import crypto from '@/lib/crypto';

class Account extends Model {
  public id!: number;
  public userId!: number;
  public socialDomain?: string;
  public socialToken?: string;
  public email?: string;
  public password?: string;

  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
  public readonly deletedAt!: Date;

  public async verifyPassword(password: string) {
    if (!this.password) {
      await this.reload({ attributes: { include: ['password'] } });
    }
    const matched = this.password === crypto.createHash(password);
    this.set('password', undefined);
    return matched;
  }
}

Account.init(
  {
    socialDomain: { type: DataTypes.STRING },
    socialToken: { type: DataTypes.STRING },
    email: { type: DataTypes.STRING },
    password: { type: DataTypes.STRING },
    // userId: { type: DataTypes.INTEGER }, // generated by association
  },
  {
    indexes: [{ fields: ['id'] }, { fields: ['email'] }],
    sequelize,
    paranoid: true,
    freezeTableName: true,
    defaultScope: { attributes: { exclude: ['password'] } },
  },
);

Account.beforeSave((account) => {
  if (account.password) {
    account.set('password', crypto.createHash(account.password));
  }
});

export default Account;
